### ISSUE TITLE
Its not really a issue but more 

### ISSUE THREAD

**Issue by leroygumede** [bitrise-samples/ionic-2#1]
Its not really a issue but more of confusion.
I keep on getting the following Error: 

```
(0) Change workdir to ionic project dir                                      |
+------------------------------------------------------------------------------+
| id: change-workdir                                                           |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-01-24T10:25:50Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Path (./medicine-price-registry-mobile) doesn't exist, but is_create_path=false
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Change workdir to ionic project dir (exit code: 1)            | 1.01 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-change-workdir/issues     |
| Source: https://github.com/bitrise-io/steps-change-workdir   
```

I know it has to do with `bitrise.yml`

```
  envs:
  - IONIC_PROJ_DIR_PATH: ./medicine-price-registry-mobile
  # for iOS
  - BITRISE_PROJECT_PATH: ./platforms/ios/medic.xcodeproj
  - BITRISE_SCHEME: medicine-price-registry-mobile
```

IONIC_PROJ_DIR_PATH is our root github directory right ?
